#!/bin/bash
# This include file has been generated by: mk-inc-dirs.sh

__base_dir='/Users/captain/workspaces/workspace-ai/claude-ldraw-skill/ldraw-skill'
bin_dir="$__base_dir/bin"
include_dir="$__base_dir/include"

dist_dir="$__base_dir/dist"

skill_builder_dir="$dist_dir/ldraw-builder"
references_dir="$skill_builder_dir/references"
scripts_dir="$skill_builder_dir/scripts"

ldraw_ai_dir="$__base_dir/../../ldraw-ai"
ldraw_ai_dir="$(realpath "$ldraw_ai_dir")"
ldraw_tools_dir="$ldraw_ai_dir/tools"
ldraw_grammars_dir="$ldraw_ai_dir/grammars"
ldraw_lark_dir="$ldraw_grammars_dir/lark"
ldraw_parser_dir="$ldraw_lark_dir/python"


